// src/components/sections/Footer.tsx
import { FaGithub } from "react-icons/fa";

const Footer = () => {
  const skillsFront = [
    {
      tech: "React",
      icon: "bx bxl-react",
    },
    {
      tech: "TypeScript",
      icon: "bx bxl-typescript",
    },
    {
      tech: "Tailwind CSS",
      icon: "bx bxl-tailwind-css",
    },
  ];

  return (
    <footer className="bg-blue-800/5 py-12 px-4 sm:px-6 lg:px-8 text-white/80 border-t border-mainTheme/20 shadow-2xl shadow-mainTheme">
      <div className="container mx-auto max-w-6xl">
        {/* Grid para as principais seções do footer */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-10 md:gap-8 text-center md:text-left">
          {/* Seção 1: Tecnologias Usadas */}
          <div className="flex flex-col items-center md:items-start">
            <h3 className="text-xl md:text-3xl mb-5 text-myWhite/80 font-bold">
              Site desenvolvido com:
            </h3>
            <div className="flex justify-center md:justify-start items-center gap-7 flex-wrap">
              {skillsFront.map((skill, index) => (
                <span
                  key={index}
                  className="flex flex-col justify-center items-center text-mainTheme"
                >
                  <i className={`${skill.icon} text-4xl md:text-5xl`}></i>
                  <span className="text-sm font-semibold text-myWhite/50 mt-1">
                    {skill.tech}
                  </span>
                </span>
              ))}
            </div>
          </div>

          {/* Seção 2: Código da Página (GitHub) */}
          <div className="flex flex-col items-center md:items-start md:ml-auto">
            <h3 className="text-xl md:text-3xl mb-5 text-myWhite/80 font-bold">
              Código da página
            </h3>
            <a
              href="https://github.com/JairoLopes/MeuPortfolio"
              target="_blank"
              rel="noopener noreferrer" // Adicionado para segurança em target="_blank"
              className="hover:scale-110 transition-transform duration-300"
            >
              <FaGithub size={40} className="text-mainTheme" />
            </a>
          </div>
        </div>

        {/* Linha separadora */}
        <hr className="border-gray-700 my-10" />

        {/* Direitos Autorais e Nome do Desenvolvedor */}
        <div className="text-center text-sm">
          <p>&copy; {new Date().getFullYear()} Todos os direitos reservados.</p>
          <p className="mt-2">
            Desenvolvido por{" "}
            <a
              href="https://jairolopes-dev.vercel.app/" // Assumindo que este é o link do seu portfólio
              target="_blank"
              rel="noopener noreferrer"
              className="text-mainTheme text-lg transition-colors duration-300 font-semibold hover:underline" // Removi o animate-pulse, mas você pode adicionar se quiser
            >
              Jairo Lopes
            </a>
          </p>
        </div>
      </div>
    </footer>
  );
};

export default Footer;

// src/components/Footer.vue
<script setup lang="ts">
// Dados das tecnologias usadas
const skillsFront = [
  {
    tech: 'Vue.js',
    icon: 'vi-file-type-vue',
  },
  {
    tech: 'TypeScript',
    icon: 'vi-file-type-typescript-official',
  },
  {
    tech: 'Tailwind CSS',
    icon: 'vi-file-type-tailwind',
  },
]

// Ícone do GitHub
const githubIcon = 'io-logo-github'
</script>

<template>
  <footer
    class="bg-blue-800/5 py-12 px-4 sm:px-6 lg:px-8 text-white/80 border-t border-mainTheme/20 shadow-2xl shadow-mainTheme"
  >
    <div class="container mx-auto max-w-6xl">
      <!-- Seção principal do footer, alinhada ao centro -->
      <div class="flex flex-col items-center gap-10 md:gap-12 text-center">
        <!-- Tecnologias Usadas -->
        <div class="flex flex-col items-center">
          <h3 class="text-xl md:text-3xl mb-4 text-myWhite/80 font-bold">
            Página desenvolvida com:
          </h3>

          <!-- Container que engloba os Icones -->
          <div class="flex justify-center items-center gap-7 flex-wrap mt-10">
            <!-- Irá iterar o array de skills e estiliza-las cada uma nessa span -->
            <span
              v-for="(skill, index) in skillsFront"
              :key="index"
              class="flex flex-col justify-center items-center text-mainTheme"
            >
              <v-icon :name="skill.icon" scale="2.2" />
              <span class="text-xs font-semibold text-myWhite/50 mt-1">
                {{ skill.tech }}
              </span>
            </span>
          </div>
        </div>

        <!-- Seção de Links -->
        <div class="flex flex-col items-center">
          <h3 class="text-xl md:text-2xl mb-4 text-myWhite/80 font-bold">Código da página</h3>
          <a
            href="https://github.com/JairoLopes/MeuPortfolio"
            target="_blank"
            rel="noopener noreferrer"
            class="hover:scale-110 transition-transform duration-300"
          >
            <v-icon :name="githubIcon" scale="2" class="text-mainTheme" />
          </a>
        </div>
      </div>

      <!-- Linha separadora -->
      <hr class="border-gray-700 my-10" />

      <!-- Direitos Autorais e Nome do Desenvolvedor -->
      <div class="text-center text-sm">
        <p class="mt-2 text-base md:text-lg font-semibold text-mainTheme">Jairo Lopes</p>
      </div>
    </div>
  </footer>
</template>
