// src/App.tsx
import { useState } from "react";
import LoadingScreen from "./components/LoadingScreen";
import NavBar from "./components/sections/NavBar";
import MobileMenu from "./components/sections/MobileMenu";
import Home from "./components/sections/Home";
import About from "./components/sections/About";
import Exp from "./components/sections/Exp";
import Projects from "./components/sections/Projects";
import Testimonial from "./components/sections/Testimonial";
import Contact from "./components/sections/Contact";
import Footer from "./components/sections/Footer";

function App() {
  const [isLoaded, setIsLoaded] = useState(false);

  /* Esse state será usado no Navbar e no MobileNavbar, ambos tem uma props que representa o estado MenuOpen e a função de estado SetMenuOpen */
  const [menuOpen, setMenuOpen] = useState(false);

  return (
    <>
      {/* Se isLoaded for false, o componente loadscreen é exibido, quando acabar o tempo de animação, ele vira true e o componente loadingScreen deixa de ser exibido*/}
      {!isLoaded && <LoadingScreen onComplete={() => setIsLoaded(true)} />}
      <div
        /* Se isloaded for true, exibe(opacity-100) todos os componentes dentro desta div, se for false, recebe opacidade 0*/
        className={`overflow-x-hidden min-h-screen transition-opacity duration-700 ${
          isLoaded ? "opacity-100" : "opacity-0"
        } bg-deepBlue text-myWhite`}
      >
        {/* Navbar --------- será exibida se dentro dela o menuOpen for true */}
        <NavBar menuOpen={menuOpen} setMenuOpen={setMenuOpen} />

        {/* MobileMenu ------------- Menu será ebixido se dentro dele o meuOpen for true */}
        <MobileMenu menuOpen={menuOpen} setMenuOpen={setMenuOpen} />

        {/* HOME ------- */}
        {/* Aqui so vai renderizar o Home quando o Loadscreen tiver finalizado, para serem visíveis as animações de carregamento */}
        {isLoaded && <Home />}

        {/* ABOUT ------- */}
        <About />

        {/* EXPERIÊNCIA */}
        <Exp />

        {/* PROJETOS */}
        <Projects />

        {/* TESTIMONIAL */}
        <Testimonial />

        {/* CONTATO */}
        <Contact />

        {/* FOOTER */}
        <Footer />
      </div>
    </>
  );
}

export default App;

// src/App.vue
<template>
  <div>
    <!-- Renderiza o LoadingScreen apenas se isLoaded for 'false' -->
    <LoadingScreen v-if="!isLoaded" @complete="handleLoadingComplete" />

    <div
      class="overflow-x-hidden min-h-screen transition-opacity duration-700 bg-deepBlue text-myWhite"
      :class="{ 'opacity-100': isLoaded, 'opacity-0': !isLoaded }"
    >
      <!-- NavBar e MobileMenu - serão renderizados sempre, mas a visibilidade interna é controlada por 'menuOpen' -->
      <NavBar :menu-open="menuOpen" @update:menu-open="menuOpen = $event" />
      <MobileMenu :menu-open="menuOpen" @update:menu-open="menuOpen = $event" />

      <!-- Componente Home -->
      <Home v-if="isLoaded" />

      <!-- Componente About -->
      <About />

      <!-- Componente Exp -->
      <Exp />

      <!-- Componente Projects -->
      <Projects />

      <!-- Componente Testimonial -->
      <Testimonial />

      <!-- Componente Contact -->
      <Contact />

      <!-- Componente Footer -->
      <Footer />
    </div>
  </div>
</template>

<script setup lang="ts">
// Importa as funções 'ref' e 'onMounted' do Vue para criar variáveis reativas.
import { ref } from 'vue'
import LoadingScreen from '@/components/LoadingScreen.vue'
import NavBar from '@/components/Navbar.vue'
import MobileMenu from '@/components/MobileMenu.vue'
import Home from '@/components/Home.vue'
import About from '@/components/About.vue'
import Exp from '@/components/Exp.vue'
import Projects from '@/components/Projects.vue'
import Testimonial from '@/components/Testimonial.vue'
import Contact from '@/components/Contact.vue'
import Footer from './components/Footer.vue'

// Define o estado reativo para controlar se a tela de carregamento já finalizou.
// Começa como 'false' para exibir a tela de carregamento inicialmente.
const isLoaded = ref(false)

// Define o estado reativo para controlar a abertura/fechamento do menu mobile.
// Começa como 'false' (fechado).
const menuOpen = ref(false)

// Função que será passada para o LoadingScreen para atualizar 'isLoaded'
const handleLoadingComplete = () => {
  isLoaded.value = true
}
</script>
